### ISSUE TITLE
Automatically populate discounts with data from https://purchasing-power-parity.com/ ?

### ISSUE THREAD

**Issue by elearningplugins** [cferdinandi/gmt-pricing-parity#1]
Hello.  I've been experimenting with your plugin and I love the implementation.  However, it's really difficult to manually populate the discount for each country.  I'm wondering if it would be possible to automatically generate an initial list on install (or by clicking on a button) to get the data from https://purchasing-power-parity.com/

Since the data likely fluctuates on a daily basis, I would only expect this to happen on activation of the plugin or perhaps by clicking on a button.  A cron job would be nice, but definitely not required.

Example:  Philippines

https://api.purchasing-power-parity.com/?target=PHL

Response currently looks like this:

`{"ppp":{"countryCodeIsoAlpha2":"PHL","currenciesCountry":[{"code":"PHP","name":"Philippine peso","symbol":"₱"}],"countryCodeIsoAlpha3":"PHL","currencyMain":{"exchangeRate":50.833879,"code":"PHP","name":"Philippine peso","symbol":"₱"},"ppp":18.29,"pppConversionFactor":0.35979941644823127}}`

I believe the discount % would basically be equal to:  100 - pppConversionFactor.  In this case, it would be about 64% off.

So, if my product is $100 in the US, it should be around $36 in Philippines.

(Note:  my math may be way off here.  it's almost midnight my local time.)

**Comment by cferdinandi** [comment]
Love the idea, but can't find any details from that API on where the information comes from. My research into PPI (Purchasing Power Indexes) is that it's very difficult to calculate. Even pros struggle with it.

I couldn't find any good databases online, with many folks deferring to the "Big Mac Index," ie. what a Big Mac costs in any particular country relative to the US.

Beyond that, I may want to offer a different discount than what a PPI provides, and I may not want to offer a discount for some countries at all.

This was, first and foremost, built for my own business, and I'm not keen to do any work on it that doesn't solve immediate problems I face. 

However, I'd be delighted to see folks fork it and modify it to meet their own needs. If you think the level of effort in integrating a third-party API for this is less than the work involved in manually adding discounts, I'd love to see what you come up with! 😎
